export const quizzes = [
    {
        id:1,
        title:"4+4=?",
        answers:[
            {answer1:8},
            {answer2:4},
            {answer3:2},
            {answer4:12},
        ],
        trueIndex:0,
        answered:null
    },
    {
        id:2,
        title:"2+12=?",
        answers:[
            {answer1:8},
            {answer2:14},
            {answer3:22},
            {answer4:15},
        ],
        trueIndex:1,
        answered:null
    },
    {
        id:3,
        title:"3+9=?",
        answers:[
            {answer1:8},
            {answer2:4},
            {answer3:2},
            {answer4:12},
        ],
        trueIndex:3,
        answered:null
    },
    {
        id:4,
        title:"5*5=?",
        answers:[
            {answer1:33},
            {answer2:12},
            {answer3:25},
            {answer4:30},
        ],
        trueIndex:2,
        answered:null
    },
    {
        id:5,
        title:"9/3=?",
        answers:[
            {answer1:4},
            {answer2:3},
            {answer3:5},
            {answer4:2},
        ],
        trueIndex:1,
        answered:null
    },
    {
        id:6,
        title:"96-34=?",
        answers:[
            {answer1:72},
            {answer2:58},
            {answer3:62},
            {answer4:67},
        ],
        trueIndex:2,
        answered:null

    },
    {
        id:7,
        title:"44+44=?",
        answers:[
            {answer1:88},
            {answer2:66},
            {answer3:77},
            {answer4:99},
        ],
        trueIndex:0,
        answered:null

    },
    {
        id:8,
        title:"55-23=?",
        answers:[
            {answer1:31},
            {answer2:32},
            {answer3:33},
            {answer4:34},
        ],
        trueIndex:1,
        answered:null
    },
    {
        id:9,
        title:"33/3=?",
        answers:[
            {answer1:12},
            {answer2:10},
            {answer3:11},
            {answer4:14},
        ],
        trueIndex:2,
        answered:null
    },
    {
        id:10,
        title:"12*12=?",
        answers:[
            {answer1:124},
            {answer2:148},
            {answer3:152},
            {answer4:144},
        ],
        trueIndex:3,
        answered:null
    },
  ];